ts-lint workflow
y047aka/elm-emaki pull request #14
Opened 2023-10-12 15:46 UTC by tsukimizake

- PRのオープンなどでprettierでのチェックをするようになります
- ts,md,ymlを対象にしています

2023-10-12 15:47 UTC, tsukimizake commented on .github/workflows/lint.yml
> +    shell: nu {0}
nushell上で実行します
今は全く意味ないけれどif文一つでも書くことがあったら恩恵を感じられます（予言）

2023-10-12 15:48 UTC, tsukimizake commented on cli/main.ts
> +    { cwd: ELM_EMAKI_PROJECT_ROOT },
ケツカンマ付けるのが正式なのか 🤔

2023-10-12 16:33 UTC, y047aka commented on cli/main.ts
> +    { cwd: ELM_EMAKI_PROJECT_ROOT },
正式というかPrettierのデフォルトか。
気に入らなければ設定ファイルでカスタマイズしても良いと思う（私はどちらでもいいので、より思想ある人たちに委ねる）

2023-10-12 23:34 UTC, tsukimizake commented on cli/main.ts
> +    { cwd: ELM_EMAKI_PROJECT_ROOT },
カンマないとwarnが出てしまうな

```sh
~/emaki > git diff                                                                                                                                                   10/13/2023 08:31:54 AM
diff --git a/cli/main.ts b/cli/main.ts
index 6afb97e..dbaf21e 100755
--- a/cli/main.ts
+++ b/cli/main.ts
@@ -17,7 +17,7 @@ async function main(): Promise<void> {
 
   await promisify(child_process.exec)(
     "npx elm make src/Main.elm --output=output/index.html",
-    { cwd: ELM_EMAKI_PROJECT_ROOT },
+    { cwd: ELM_EMAKI_PROJECT_ROOT }
   );
 
   const port = parseInt(process.env["EMAKI_PORT"] || "", 10) || 8000;
~/emaki > npx prettier --check **/*.ts                                                                                                                               10/13/2023 08:29:45 AM
Checking formatting...
[warn] cli/main.ts
[warn] Code style issues found in the above file. Run Prettier to fix.
~/emaki > npx prettier --version                                                                                                                                     10/13/2023 08:29:56 AM
3.0.3
```

https://prettier.io/docs/en/options.html#trailing-commas ver3からデフォルトで付けるようになったらしい？(へんなの)

2023-10-12 23:40 UTC, tsukimizake commented on .github/workflows/lint.yml
> +          prettier_options: --check **/*.{ts,md,yml}
https://github.com/marketplace/actions/checkout#push-a-commit-using-the-built-in-token
--writeしてコミット追加するくんもやったことがあるのだけど、以前やってみたらいちいちgit pull --rebaseが必要であんまり手間が変わらないような感じだった記憶

2023-10-12 23:42 UTC, tsukimizake commented
https://github.com/y047aka/elm-emaki/pull/2#discussion_r1349619782 npmコマンド作ってそれ経由で呼ぶほうが良さそう、たぶん今晩直す

2023-10-13 00:14 UTC, y047aka commented on cli/main.ts
> +    { cwd: ELM_EMAKI_PROJECT_ROOT },
VSCodeの拡張では最近v3に上げたけど、revertされて結局v2.8.8を使っているらしい。
https://github.com/prettier/prettier-vscode/commit/ad1d008ff81a5a85b783e3016ad136e88d149abf

2023-10-13 00:47 UTC, y047aka commented
biomeを試すのも選択肢なのかもしれない

2023-10-13 03:44 UTC, pxfnc commented on cli/main.ts
> +    { cwd: ELM_EMAKI_PROJECT_ROOT },
`npm i -D prettier` でnode_modules以下に入れておけばvscode拡張がそれを参照するようになるはずなので、package.jsonのdevDependenciesに入れちゃって良さそうです(どうせciで回すわけですし)

2023-10-13 03:45 UTC, pxfnc commented
npm package scriptで回す案、賛成です！

2023-10-14 02:10 UTC, tsukimizake commented
npm script化ヨシ

2023-10-14 02:16 UTC, y047aka commented on .github/workflows/lint.yml
> +          node-version: 16
瑣末ですが、v18以上にしたい
https://github.com/nodejs/release#release-schedule
![schedule](https://github.com/y047aka/elm-emaki/assets/7818994/fee749ec-95e5-468b-a85e-aea1af14c851)

2023-10-14 02:40 UTC, tsukimizake commented on .github/workflows/lint.yml
> +          node-version: 16
🦀  7599b18

2023-10-14 02:50 UTC, y047aka approved these changes
すでに prettier v3.0.3 がstable扱いなので v2に留める選択はしないほうが良いと思うけど、このPRはここまででマージできそうです。

v3を導入する場合には prettierrc を導入してVSCode側との動作を揃えることになるかな。
https://github.com/y047aka/elm-emaki/pull/14#discussion_r1359079508

2023-10-14 02:59 UTC, y047aka commented on cli/main.ts
> +    { cwd: ELM_EMAKI_PROJECT_ROOT },
ローカルでcheckoutしてv3.0.3にした場合の挙動を試してみました。
たしかにvscode拡張がv3.0.3を参照しているようですが、ルールは `"trailingComma": "es5"` が優先されるように見えます。
v3.0.3を使う場合には、この項目の設定も変更する必要がありそうです。

```
["INFO" - 11:54:16] Extension Name: esbenp.prettier-vscode.
["INFO" - 11:54:16] Extension Version: 10.1.0.
["INFO" - 11:54:19] Formatting file:///Users/y047aka/Github/elm-emaki/cli/main.ts
["INFO" - 11:54:19] PrettierInstance:
{
  "modulePath": "/Users/y047aka/Github/elm-emaki/node_modules/prettier/index.cjs",
  "importResolver": {},
  "callMethodResolvers": {},
  "currentCallMethodId": 2,
  "version": "3.0.3"
}
["INFO" - 11:54:19] Using ignore file (if present) at /Users/y047aka/Github/elm-emaki/.prettierignore
["INFO" - 11:54:19] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 11:54:19] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 11:54:19] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "embeddedLanguageFormatting": "auto",
  "vueIndentScriptAndStyle": false,
  "filepath": "/Users/y047aka/Github/elm-emaki/cli/main.ts",
  "parser": "typescript"
}
["INFO" - 11:54:19] Formatting completed in 90ms.
```

2023-10-14 05:00 UTC, tsukimizake commented
mom install -D prettierしたらこのバージョンだった

2023-10-14 05:35 UTC, y047aka requested changes
となると話は変わってきて、prettierを入れ直して^2.8.8にしましょう。

2023-10-14 14:46 UTC, tsukimizake commented
[63d4d0f](https://github.com/y047aka/elm-emaki/pull/14/commits/63d4d0fdb044e741e191903f2593d67a292b0999) 2.8.8

2023-10-14 15:40 UTC, y047aka approved these changes
良さそう！

2023-10-14 16:05 UTC, y047aka commented
マージしちゃいます！cc: @pxfnc 

- マージの単位として適当、かつ動作も問題なさそう
    - 後続のPull Pequestもopenになっているので修正必要な箇所あればそちらで対応
        - https://github.com/y047aka/elm-emaki/pull/16
    - Prettier v3に対する扱いについては、方針提案またはPR歓迎です！
- 各人が実装に集中できるように、レビュー負荷を下げていきたい
    - ある程度動作確認できていれば、積極的にマージしてOK（まだ開発初期段階なので）
        - そのためにもCIやテストは充実させたい
    - レビューに参加できなかった場合も、後からのコメントは大歓迎！！！

2023-10-14 16:06 UTC, merged