[example] Initial setup
y047aka/elm-emaki pull request #15
Opened 2023-10-13 16:37 UTC by y047aka

example ディレクトリに elm-emaki のサンプルプロジェクトを作成します。

2023-10-14 12:14 UTC, y047aka commented on package.json
> +    "run-pty": "^4.1.0",
サンプルアプリケーションのビルドにelm-watchを使用します。

まずはリポジトリルートのpackage.jsonに追記していますが、npm workspaceを活用してexampleディレクトリに専用のpackage.jsonを作るようにしたい。
賛同得られたら追加で作業します。

2023-10-14 12:15 UTC, y047aka commented on example/app.ts
https://github.com/lydell/elm-watch/blob/main/example/app.ts

2023-10-14 12:22 UTC, y047aka commented on example/src/Main.elm
> +    -> Html msg
rio-grandeでは [configAndPreview](https://github.com/y047aka/rio-grande/blob/ee923fa8704d9991d35cd4c55d50e2622b786a7a/src/ConfigAndPreview.elm#L32) として定義していたview関数をよりシンプルな形で再実装しています。
従来の実装を見直しながら、少しずつ機能追加します。

2023-10-14 12:44 UTC, y047aka commented on package/src/Css/Extra.elm
> +    property "place-items" "center"
[`Css.alignItems`](https://github.com/rtfeldman/elm-css/blob/551376deabbfa50eec40a0a735941b4edf7ea592/src/Css.elm#L3439-L3441) に倣って

```elm
placeItems : (ExplicitLength IncompatibleUnits -> Style) -> Style
placeItems fn =
    getOverloadedProperty "alignItems" "align-items" (fn lengthForOverloadedProperty)
```

にできれば素直なんだけど、elm-cssの外では `getOverloadedProperty` を模倣することができず断念。
`place-*` を使うのはセンタリング用途がほとんどなので（それ以外で使う恩恵はあまりない）、`Css.displayFlex` に倣って `Style` 型として実装しました。

---

```css
.container {
  display: grid;
  place-items: center;
}
```
のように、最小記述でセンタリングを実装するイディオムとして普及しています。

参考：https://zenn.dev/moneyforward/articles/css-grid-centering

2023-10-14 12:46 UTC, y047aka commented on package/src/Css/Palette.elm
> +paletteWith border p =
記述が少し冗長なので簡略化。
今後、ドロップシャドウを考慮する時にまた見直します。

2023-10-14 13:31 UTC, y047aka commented on example/src/Main.elm
> +resetCSS : Html msg
最小限のリセットCSSを記述しました。
私が公開している[y047aka/elm-reset-css](https://package.elm-lang.org/packages/y047aka/elm-reset-css/) を使っても良いんだけど、

- elm-emakiをelm packageとして公開する時の依存に含めたくない
- サンプルアプリケーションをシンプルに保ちたい
    - y047aka/elm-reset-css の使い方を気にしてほしくない

などの理由から見送りました。

シンプルにするという観点では、Elmアプリケーションには記述せずに`reset.css`を作って読み込むようにするほうが良いだろうなという予想もある。

2023-10-14 13:42 UTC, y047aka commented on example/app.ts
何もしていないのに outdated になった（？）

2023-10-18 01:39 UTC, tsukimizake approved these changes

2023-10-18 04:54 UTC, pxfnc commented on package.json
> +    "run-pty": "^4.1.0",
この段階でexampleにpackage.jsonを作成し、プロジェクトルートのpackage.jsonの依存を変えないようにするほうが良いと考えています


exampleの役割はいくつかあって

* 使い方のイメージを掴むため
* 動くプロジェクトディレクトリ構成を示すため
  * ユーザは、example動かなかったらメンテナに頑張ってもらうし、exampleが動くのであれば自分のインストール方法に間違いがあることに気づける

という理由がありますが、rootにしてしまうとexample以下だけで完結しなくなってしまうので、少なくとも独立してビルド出来る形でmainに取り込みたいです

npm workspaceを使うか使わないかについてですが、npm workspaceを使うメリット、複数のパッケージのdepsを固定したい等の理由が無いのであればworkspaceとして管理することも無いのかなぁという気持ちがあるので、一旦example/package.jsonだけ作成するのが良いかなと思います！

2023-10-18 04:56 UTC, pxfnc requested changes

2023-10-18 04:56 UTC, pxfnc commented on package.json
> +    "run-pty": "^4.1.0",
```suggestion
    "prettier": "^2.8.8",
```

2023-10-18 04:56 UTC, pxfnc commented on package.json
> +    "run-pty": "^4.1.0",
https://github.com/y047aka/elm-emaki/pull/15#discussion_r1363173804

2023-10-18 14:31 UTC, y047aka commented on package.json
> +    "run-pty": "^4.1.0",
https://github.com/y047aka/elm-emaki/pull/15/commits/02c814ce94148fa3f4afd23b4ad88cb5ee6491c8 修正しました！

2023-10-18 14:33 UTC, y047aka commented on package.json
> +    "run-pty": "^4.1.0",
意義ありません！
https://github.com/y047aka/elm-emaki/pull/15/commits/02c814ce94148fa3f4afd23b4ad88cb5ee6491c8 にて、そのとおりに修正しました。

2023-11-04 13:06 UTC, pxfnc approved these changes
LGTMです！

2023-11-05 11:25 UTC, merged